export const SAMPLE_PLANT = [
  {
    id: 1,
    name: "Golden Barrel Cactus",
    category: "Cactus",
    s_name: "Echinocactus grusonii",
    price: 22.99,
    img: "/img/cactus1.png",
  },
  {
    id: 2,
    name: "Prickly Pear",
    category: "Cactus",
    s_name: "Opuntia spp.",
    price: 18.5,
    img: "/img/cactus2.png",
  },
  {
    id: 3,
    name: "Saguaro",
    category: "Cactus",
    s_name: "Carnegiea gigantea",
    price: 89.99,
    img: "/img/cactus3.png",
  },
  {
    id: 4,
    name: "Moon Cactus",
    category: "Cactus",
    s_name: "Gymnocalycium mihanovichii",
    price: 12.99,
    img: "/img/cactus4.png",
  },
  {
    id: 5,
    name: "Old Lady Cactus",
    category: "Cactus",
    s_name: "Mammillaria hahniana",
    price: 15.75,
    img: "/img/cactus1.png",
  },
  {
    id: 6,
    name: "Snake Plant",
    category: "Office Plant",
    s_name: "Sansevieria trifasciata",
    price: 29.99,
    img: "/img/office1.png",
  },
  {
    id: 7,
    name: "ZZ Plant",
    category: "Office Plant",
    s_name: "Zamioculcas zamiifolia",
    price: 34.5,
    img: "/img/office2.png",
  },
  {
    id: 8,
    name: "Peace Lily",
    category: "Office Plant",
    s_name: "Spathiphyllum wallisii",
    price: 27.99,
    img: "/img/office3.png",
  },
  {
    id: 9,
    name: "Pothos",
    category: "Office Plant",
    s_name: "Epipremnum aureum",
    price: 19.99,
    img: "/img/office4.png",
  },
  {
    id: 10,
    name: "Dracaena",
    category: "Office Plant",
    s_name: "Dracaena marginata",
    price: 39.99,
    img: "/img/office5.png",
  },
  {
    id: 11,
    name: "Monstera",
    category: "Indoor Plant",
    s_name: "Monstera deliciosa",
    price: 49.99,
    img: "/img/office6.png",
  },
  {
    id: 12,
    name: "Fiddle Leaf Fig",
    category: "Indoor Plant",
    s_name: "Ficus lyrata",
    price: 59.99,
    img: "/img/office7.png",
  },
  {
    id: 13,
    name: "Rubber Plant",
    category: "Indoor Plant",
    s_name: "Ficus elastica",
    price: 34.99,
    img: "/img/office1.png",
  },
  {
    id: 14,
    name: "Bird of Paradise",
    category: "Indoor Plant",
    s_name: "Strelitzia reginae",
    price: 69.99,
    img: "/img/office3.png",
  },
  {
    id: 15,
    name: "Chinese Money Plant",
    category: "Indoor Plant",
    s_name: "Pilea peperomioides",
    price: 24.99,
    img: "/img/cart-1.png",
  },
  {
    id: 16,
    name: "Lemon Tree",
    category: "Fruit Plant",
    s_name: "Citrus limon",
    price: 44.99,
    img: "/img/malbery.png",
  },
  {
    id: 17,
    name: "Strawberry Plant",
    category: "Fruit Plant",
    s_name: "Fragaria × ananassa",
    price: 14.99,
    img: "/img/tomato.png",
  },
  {
    id: 18,
    name: "Blueberry Bush",
    category: "Fruit Plant",
    s_name: "Vaccinium corymbosum",
    price: 39.99,
    img: "/img/apple.png",
  },
  {
    id: 19,
    name: "Dwarf Banana",
    category: "Fruit Plant",
    s_name: "Musa acuminata",
    price: 54.99,
    img: "/img/Redapple.png",
  },
  {
    id: 20,
    name: "Fig Tree",
    category: "Fruit Plant",
    s_name: "Ficus carica",
    price: 49.99,
    img: "/img/cherry.png",
  },
  {
    id: 21,
    name: "Bunny Ears Cactus",
    category: "Cactus",
    s_name: "Opuntia microdasys",
    price: 16.99,
    img: "/img/office3.png",
  },
  {
    id: 22,
    name: "Christmas Cactus",
    category: "Cactus",
    s_name: "Schlumbergera truncata",
    price: 19.99,
    img: "/img/office4.png",
  },
  {
    id: 23,
    name: "Spider Plant",
    category: "Office Plant",
    s_name: "Chlorophytum comosum",
    price: 17.99,
    img: "/img/office5.png",
  },
  {
    id: 24,
    name: "Philodendron",
    category: "Office Plant",
    s_name: "Philodendron scandens",
    price: 24.99,
    img: "/img/office6.png",
  },
  {
    id: 25,
    name: "Calathea",
    category: "Indoor Plant",
    s_name: "Calathea orbifolia",
    price: 29.99,
    img: "/img/office7.png",
  },
  {
    id: 26,
    name: "Aloe Vera",
    category: "Indoor Plant",
    s_name: "Aloe barbadensis miller",
    price: 12.99,
    img: "/img/office2.png",
  },
  {
    id: 27,
    name: "Apple",
    category: "Fruit Plant",
    s_name: "Persea americana",
    price: 59.99,
    img: "/img/apple.png",
  },
  {
    id: 28,
    name: "Berry Berry",
    category: "Fruit Plant",
    s_name: "Hylocereus undatus",
    price: 34.99,
    img: "/img/berry.png",
  },
  {
    id: 29,
    name: "Cherry ",
    category: "Fruit Plant",
    s_name: "Punica granatum",
    price: 49.99,
    img: "/img/Cherry.png",
  },
  {
    id: 30,
    name: "Mal-Berry",
    category: "Fruit Plant",
    s_name: "Citrus × meyeri",
    price: 54.99,
    img: "/img/malbery.png",
  },
  {
    id: 30,
    name: "PaPaYa",
    category: "Fruit Plant",
    s_name: "Citrus × meyeri",
    price: 54.99,
    img: "/img/pepeya.png",
  },
  {
    id: 30,
    name: "Red Apple",
    category: "Fruit Plant",
    s_name: "Citrus × meyeri",
    price: 54.99,
    img: "/img/Redapple.png",
  },
  {
    id: 30,
    name: "Cherry Tomato",
    category: "Fruit Plant",
    s_name: "Citrus × meyeri",
    price: 54.99,
    img: "/img/tomato.png",
  },
];
