export const SAMPLE_SEEDS = [
  {
    id: 201,
    name: "Heirloom Tomato Seeds",
    price: 3.99,
    discount: 2.99,
    type: "Vegetable Seeds",
    description:
      "Juicy, flavorful tomatoes. 50+ seeds per packet. Matures in 75-85 days. Perfect for salads and sauces.",
    image: "/images/tomato-seeds.jpg",
    category: "Vegetables",
    germination: "7-14 days",
    season: "Spring/Summer",
  },
  {
    id: 202,
    name: "Sunflower 'Giant Russian'",
    price: 2.5,
    discount: null,
    type: "Flower Seeds",
    description:
      "Massive 12-15ft blooms. 30 seeds. Attracts pollinators. Drought-tolerant once established.",
    image: "/images/sunflower-seeds.jpg",
    category: "Flowers",
    germination: "10-21 days",
    season: "Spring",
  },
  {
    id: 203,
    name: "Basil 'Genovese'",
    price: 2.25,
    discount: 1.99,
    type: "Herb Seeds",
    description:
      "Classic Italian basil. 100+ seeds. Fragrant leaves perfect for pesto and cooking.",
    image: "/images/basil-seeds.jpg",
    category: "Herbs",
    germination: "5-10 days",
    season: "Spring/Summer",
  },
  {
    id: 204,
    name: "Rainbow Carrot Mix",
    price: 4.25,
    discount: 3.75,
    type: "Root Vegetable Seeds",
    description:
      "Colorful blend of purple, yellow, and orange carrots. 300 seeds. Sweet and crunchy.",
    image: "/images/carrot-seeds.jpg",
    category: "Vegetables",
    germination: "14-21 days",
    season: "Cool Season",
  },
  {
    id: 205,
    name: "Wildflower Meadow Mix",
    price: 5.99,
    discount: 4.99,
    type: "Flower Seed Mix",
    description:
      "15+ native species. Covers 10 sq ft. Low-maintenance and pollinator-friendly.",
    image: "/images/wildflower-seeds.jpg",
    category: "Flowers",
    germination: "7-30 days",
    season: "Any Season",
  },
  {
    id: 206,
    name: "Jalapeño Pepper",
    price: 3.25,
    discount: null,
    type: "Pepper Seeds",
    description:
      "Medium-hot peppers. 25 seeds. Great for salsas and pickling. Matures in 70-80 days.",
    image: "/images/pepper-seeds.jpg",
    category: "Vegetables",
    germination: "10-20 days",
    season: "Warm Season",
  },
  {
    id: 207,
    name: "Lavender 'English'",
    price: 3.75,
    discount: 3.25,
    type: "Herb Seeds",
    description:
      "Fragrant purple flowers. 50 seeds. Drought-resistant. Perfect for borders and crafts.",
    image: "/images/lavender-seeds.jpg",
    category: "Herbs",
    germination: "14-28 days",
    season: "Spring",
  },
  {
    id: 208,
    name: "Microgreen Salad Mix",
    price: 4.5,
    discount: 3.99,
    type: "Greens Seeds",
    description:
      "Fast-growing blend of radish, broccoli, and kale. Ready to harvest in 10-14 days.",
    image: "/images/microgreen-seeds.jpg",
    category: "Greens",
    germination: "2-5 days",
    season: "Indoor/Year-Round",
  },
  {
    id: 209,
    name: "Dwarf Cherry Tomato 'Tiny Tim'",
    price: 4.25,
    discount: 3.5,
    type: "Container Tomato Seeds",
    description:
      "Compact 12-inch plants yield sweet cherry tomatoes. 50+ seeds. Perfect for pots/balconies. Matures in 45-60 days.",
    image: "/images/dwarf-tomato.jpg",
    category: "Vegetables",
    germination: "5-10 days",
    season: "Spring/Summer",
    sunRequirements: "Full Sun",
  },
  {
    id: 210,
    name: "Buttercrunch Lettuce",
    price: 2.99,
    discount: null,
    type: "Lettuce Seeds",
    description:
      "Tender, sweet heads. 200 seeds. Slow to bolt. Harvest in 50-60 days. Ideal for continuous planting.",
    image: "/images/buttercrunch-lettuce.jpg",
    category: "Greens",
    germination: "7-14 days",
    season: "Cool Season",
    sunRequirements: "Partial Shade",
  },
  {
    id: 211,
    name: "Moonflower Vine",
    price: 3.75,
    discount: 3.25,
    type: "Flowering Vine Seeds",
    description:
      "Night-blooming fragrant white flowers. 15 seeds. Climbs 10-15ft. Attracts moths and pollinators.",
    image: "/images/moonflower.jpg",
    category: "Flowers",
    germination: "14-21 days",
    season: "Summer",
    sunRequirements: "Full Sun",
  },
  {
    id: 212,
    name: "Rainbow Swiss Chard",
    price: 3.5,
    discount: 2.99,
    type: "Leafy Green Seeds",
    description:
      "Colorful stems (red/yellow/pink). 100 seeds. Heat-tolerant. Harvest leaves all season.",
    image: "/images/rainbow-chard.jpg",
    category: "Greens",
    germination: "5-10 days",
    season: "Spring/Fall",
    sunRequirements: "Full Sun to Partial Shade",
  },
  {
    id: 213,
    name: "Cucumber 'Straight Eight'",
    price: 3.25,
    discount: null,
    type: "Cucumber Seeds",
    description:
      "Classic 8-inch slicing cukes. 30 seeds. Disease-resistant. Matures in 55-60 days.",
    image: "/images/cucumber-seeds.jpg",
    category: "Vegetables",
    germination: "7-14 days",
    season: "Warm Season",
    sunRequirements: "Full Sun",
  },
  {
    id: 214,
    name: "Bee Balm 'Bergamo'",
    price: 4.5,
    discount: 3.99,
    type: "Pollinator Flower Seeds",
    description:
      "Deer-resistant perennial with pink blooms. 50 seeds. Attracts bees/hummingbirds. Medicinal uses.",
    image: "/images/bee-balm.jpg",
    category: "Flowers",
    germination: "10-30 days",
    season: "Spring/Summer",
    sunRequirements: "Full Sun",
  },
  {
    id: 215,
    name: "Purple Podded Bush Bean",
    price: 2.75,
    discount: 2.25,
    type: "Bean Seeds",
    description:
      "Vibrant purple pods turn green when cooked. 40 seeds. Compact 18-inch plants. Matures in 50 days.",
    image: "/images/purple-beans.jpg",
    category: "Vegetables",
    germination: "7-14 days",
    season: "Warm Season",
    sunRequirements: "Full Sun",
  },
  {
    id: 216,
    name: "Mammoth Dill",
    price: 2.5,
    discount: null,
    type: "Culinary Herb Seeds",
    description:
      "Feathery foliage for pickling and fish dishes. 200 seeds. Grows to 3ft. Self-seeds easily.",
    image: "/images/dill-seeds.jpg",
    category: "Herbs",
    germination: "10-21 days",
    season: "Spring/Summer",
    sunRequirements: "Full Sun",
  },
  {
    id: 217,
    name: "Black Beauty Zucchini",
    price: 3.99,
    discount: 3.49,
    type: "Squash Seeds",
    description:
      "High-yielding dark green zucchini. 25 seeds. Matures in 45-55 days. Great for grilling.",
    image: "/images/zucchini-seeds.jpg",
    category: "Vegetables",
    germination: "7-14 days",
    season: "Warm Season",
    sunRequirements: "Full Sun",
  },
  {
    id: 218,
    name: "California Poppy Mix",
    price: 3.25,
    discount: 2.75,
    type: "Wildflower Seeds",
    description:
      "Drought-tolerant orange/yellow blooms. 500 seeds. Covers 20 sq ft. State flower of California.",
    image: "/images/poppy-mix.jpg",
    category: "Flowers",
    germination: "14-30 days",
    season: "Fall/Spring",
    sunRequirements: "Full Sun",
  },
  {
    id: 219,
    name: "Thai Basil 'Siam Queen'",
    price: 3.5,
    discount: null,
    type: "Asian Herb Seeds",
    description:
      "Spicy anise flavor for curries and teas. 100 seeds. Purple stems. Heat-loving.",
    image: "/images/thai-basil.jpg",
    category: "Herbs",
    germination: "5-14 days",
    season: "Warm Season",
    sunRequirements: "Full Sun",
  },
  {
    id: 220,
    name: "Detroit Dark Red Beet",
    price: 2.99,
    discount: 2.5,
    type: "Root Vegetable Seeds",
    description:
      "Heirloom beets with sweet flavor. 100 seeds. Greens are edible. Matures in 55-65 days.",
    image: "/images/beet-seeds.jpg",
    category: "Vegetables",
    germination: "7-14 days",
    season: "Cool Season",
    sunRequirements: "Full Sun",
  },
];